from uuid import uuid4
from typing import Literal

from langchain_core.language_models import BaseChatModel
from langchain_core.runnables import Runnable
from pydantic import BaseModel, Field

from app.graph.agents.helpers import last_message
from app.graph.state import AppState
from app.graph.types import RawTask



type IntentMap = dict[str, list[str]]

class RouterOutputSchema(BaseModel):
    current_intent: Literal["stress", "overload", "manage_task"] | None = Field(
        default=None,
        description="Overall user intent. Must strictly match one of the allowed values.",
    )
    raw_tasks: list[RawTask] = Field(
        default_factory=list,
        description="Extract EACH distinct task/event as a SEPARATE item. If user mentions 3 different tasks, output 3 items.",
    )

SYSTEM_PROMPT = """
You are the Router Agent for a schedule management system.
Your job is to identify the user's intent and extract the raw tasks they mention.

HARD RULES FOR EXTRACTION:
1. "current_intent" MUST be exactly one of: ["stress", "overload", "manage_task", null].
2. "category" MUST be exactly one of: ["serius", "santai", "biasa", "lainnya", null].
3. "task_id" is assigned by the system after extraction and must not be generated by the model.
4. "raw_input" MUST be the exact words used by the user for that specific task.
5. "raw_time" MUST capture the time phrase AND its context based on the user's sentence. Add the context in parentheses. Examples: "besok jam 9 (deadline)", "nanti malam (waktu pengerjaan yang diinginkan)", "jam 10 (waktu mulai acara/meeting)". If no time is mentioned, output null.
6. MATCH THE LANGUAGE: You MUST write the "title", "description", and "raw_time" using the exact same language and tone as the user's input.
7. SEPARATE DISTINCT TASKS: If the user mentions multiple DIFFERENT tasks, you MUST extract them as SEPARATE items in the array. 
8. NO DUPLICATES: Only merge phrases if they describe the EXACT SAME task.
9. EXTRACT VAGUE TASKS: If the user mentions a general/vague group of tasks, extract it as a separate task item and state that it's vague in the description.

INTENT SELECTION LOGIC (CRITICAL RULES):
- "manage_task": Choose this for NEUTRAL, standard scheduling requests where the user knows what to do. Example: "Tolong masukin tugasku besok jam 9", "Aku ada rapat nanti sore". No panic, no confusion.
- "overload": Choose this if the user emphasizes the QUANTITY/VOLUME of tasks. Keywords: "tugas numpuk", "banyak banget", "keriting jari". The root cause is having too much on their plate.
- "stress": Choose this if the user is in distress, panicked, OR EXPERIENCING A COGNITIVE BLOCK (e.g., "bingung", "nggak tau mulai dari mana", "ngeblank", "takut"). 
  --> IMPORTANT: Even if they mention a SPECIFIC task and deadline (e.g., "ada tugas ABL besok jam 9 tapi ga tau mulai dari mana"), CHOOSE "stress"! They need psychological help/brainstorming first before scheduling.

DESCRIPTION RULE:
For the "description" field, do not just summarize the task. You must explicitly describe:
1. What the user feels about the task (e.g., panicked, relaxed, confused).
2. What details are missing, unknown, or causing the block (e.g., unknown deadline, unknown topic, doesn't know the first step).

Examples:
Input: "aku besok ada tugas ABL nih dl-nya jam 9 tapi ga tau harus mulai dari mana"
Intent: "stress" (Because of the cognitive block "ga tau harus mulai dari mana")
Description: "Pengguna merasa bingung dan tertekan karena tidak tahu harus memulai langkah pengerjaan dari mana. Detail yang belum jelas: langkah awal dan materi tugas ABL."

Input: "besok pagi ada tugas ABL jam 9, masukin kalender ya"
Intent: "manage_task" (Neutral, direct command)
Description: "Pengguna merasa biasa/netral. Detail yang belum jelas: topik spesifik tugas ABL."
"""


def make_router(intent_map: IntentMap, llm: BaseChatModel):
    """
    Factory untuk RouterAgent.
    Tugas: klasifikasi intent dari pesan user -> update state["current_intent"].
    """

    structured_output = llm.with_structured_output(RouterOutputSchema)

    def run(state: AppState) -> dict:
        text = last_message(state)
        output = _classify(text, intent_map, structured_output)
        return output 

    return run


def _classify(
    text: str,
    intent_map: IntentMap,
    structured_output: Runnable,
) -> dict:
    """
    Klasifikasi intent + ekstrak raw tasks via structured LLM output.
    Intent divalidasi terhadap intent_map. Jika tidak valid/ambigu, pakai None.
    """
    result = structured_output.invoke(
        [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ]
    )

    if hasattr(result, "model_dump"):
        result = result.model_dump()

    if not isinstance(result, dict):
        return {"current_intent": None, "raw_tasks": []}

    raw_intent = result.get("current_intent")
    valid_intents = set(intent_map.keys())
    intent = raw_intent if raw_intent in valid_intents else None

    raw_tasks = result.get("raw_tasks")
    if not isinstance(raw_tasks, list):
        raw_tasks = []

    normalized_tasks: list[dict] = []
    for task in raw_tasks:
        if hasattr(task, "model_dump"):
            normalized_task = task.model_dump()
        elif isinstance(task, dict):
            normalized_task = dict(task)
        else:
            continue

        normalized_task["task_id"] = str(uuid4())
        normalized_tasks.append(normalized_task)


    return {
        "current_intent": intent,
        "raw_tasks": normalized_tasks,
    }